import type { Funder } from "./types";

/**
 * Mock / sample funder universe relevant to a Common Courtesy-style mobility
 * nonprofit. These are FICTIONAL demo funders (names contain "(Sample)") with
 * illustrative ranges and deadlines. No real grant facts are represented here.
 *
 * Dates are relative to a ~2026 demo timeline so the deadline logic shows a mix
 * of "apply now", "prepare for next cycle", and "missed this cycle" states.
 */
export const mockFunders: Funder[] = [
  {
    id: "f-aging-services",
    name: "Silver Years Aging Services Fund (Sample)",
    type: "foundation",
    geography: "Statewide",
    reach: "state",
    interests: ["aging", "independence", "social isolation", "transportation"],
    populations: ["Seniors", "Medically vulnerable people"],
    typicalGrantRange: { min: 15000, max: 75000 },
    deadlineType: "annual",
    nextDeadline: "2026-07-15",
    applicationBurden: "medium",
    relationshipRequired: "helpful",
    requiredDocuments: ["determinationLetter", "operatingBudget", "impactReport"],
    notes: "Funds programs that help older adults age in place. Likes clear independence outcomes.",
    samplePastGrants: ["$50,000 to a rural senior meal-delivery program (sample)"],
    website: "silveryears.example.org",
    isSample: true,
  },
  {
    id: "f-disability-access",
    name: "Open Doors Disability Access Foundation (Sample)",
    type: "foundation",
    geography: "National",
    reach: "national",
    interests: ["disability", "transportation", "independence", "mobility"],
    populations: ["People with disabilities"],
    typicalGrantRange: { min: 20000, max: 100000 },
    deadlineType: "quarterly",
    nextDeadline: "2026-06-30",
    applicationBurden: "medium",
    relationshipRequired: "none",
    requiredDocuments: ["determinationLetter", "programBudget", "evaluationData"],
    notes: "Prioritizes accessible transportation and independent living. Wants evaluation data.",
    samplePastGrants: ["$80,000 for wheelchair-accessible van retrofits (sample)"],
    website: "opendoors.example.org",
    isSample: true,
  },
  {
    id: "f-healthcare-access",
    name: "Bridge to Care Health Access Foundation (Sample)",
    type: "foundation",
    geography: "Regional",
    reach: "state",
    interests: ["healthcare access", "transportation", "aging", "disability"],
    populations: ["Medically vulnerable people", "Low-income riders", "Seniors"],
    typicalGrantRange: { min: 25000, max: 150000 },
    deadlineType: "annual",
    nextDeadline: "2026-09-01",
    applicationBurden: "high",
    relationshipRequired: "helpful",
    requiredDocuments: ["determinationLetter", "auditedFinancials", "evaluationData", "impactReport"],
    notes: "Funds non-emergency medical transportation and access-to-care programs. Rigorous reporting.",
    samplePastGrants: ["$120,000 for a rides-to-dialysis pilot (sample)"],
    website: "bridgetocare.example.org",
    isSample: true,
  },
  {
    id: "f-hospital-community-benefit",
    name: "Mercy Regional Hospital Community Benefit Program (Sample)",
    type: "healthcare system",
    geography: "Local",
    reach: "local",
    interests: ["healthcare access", "transportation", "social isolation"],
    populations: ["Medically vulnerable people", "Seniors", "Low-income riders"],
    typicalGrantRange: { min: 10000, max: 60000 },
    deadlineType: "annual",
    nextDeadline: "2026-10-15",
    applicationBurden: "medium",
    relationshipRequired: "likely required",
    requiredDocuments: ["determinationLetter", "operatingBudget", "impactReport"],
    notes: "Hospital community-benefit dollars target social determinants like transportation. Relationship-driven.",
    samplePastGrants: ["$40,000 to reduce missed appointments via rides (sample)"],
    website: "mercyregional.example.org",
    isSample: true,
  },
  {
    id: "f-transportation-equity",
    name: "MoveTogether Transportation Equity Fund (Sample)",
    type: "foundation",
    geography: "National",
    reach: "national",
    interests: ["transportation", "mobility", "transportation equity", "disability", "aging"],
    populations: ["Low-income riders", "People without reliable transportation", "People with disabilities"],
    typicalGrantRange: { min: 30000, max: 120000 },
    deadlineType: "rolling",
    nextDeadline: null,
    applicationBurden: "medium",
    relationshipRequired: "none",
    requiredDocuments: ["determinationLetter", "programBudget"],
    notes: "Backs equitable mobility for people left behind by app-based transit. Rolling LOIs.",
    samplePastGrants: ["$95,000 for human-dispatch ride coordination (sample)"],
    website: "movetogether.example.org",
    isSample: true,
  },
  {
    id: "f-food-access",
    name: "Full Table Food Access Trust (Sample)",
    type: "foundation",
    geography: "Statewide",
    reach: "state",
    interests: ["food access", "transportation", "aging"],
    populations: ["Low-income riders", "Seniors"],
    typicalGrantRange: { min: 10000, max: 50000 },
    deadlineType: "quarterly",
    nextDeadline: "2026-06-10",
    applicationBurden: "low",
    relationshipRequired: "none",
    requiredDocuments: ["determinationLetter", "operatingBudget"],
    notes: "Funds projects connecting people to groceries and food banks. Light application.",
    samplePastGrants: ["$25,000 for grocery-shuttle service (sample)"],
    website: "fulltable.example.org",
    isSample: true,
  },
  {
    id: "f-community-foundation",
    name: "Greater Metro Community Foundation (Sample)",
    type: "foundation",
    geography: "Local",
    reach: "local",
    interests: ["aging", "disability", "transportation", "food access", "social isolation", "healthcare access"],
    populations: ["Seniors", "People with disabilities", "Low-income riders"],
    typicalGrantRange: { min: 5000, max: 40000 },
    deadlineType: "annual",
    nextDeadline: "2026-08-20",
    applicationBurden: "low",
    relationshipRequired: "helpful",
    requiredDocuments: ["determinationLetter", "operatingBudget", "boardList"],
    notes: "Local funder of broad community needs. Existing relationship is an advantage.",
    samplePastGrants: ["$25,000 general operating grant (sample)"],
    website: "metrocf.example.org",
    isSample: true,
  },
  {
    id: "f-corporate-mobility",
    name: "DriveForward Corporate Giving (Sample)",
    type: "corporate giving",
    geography: "National",
    reach: "national",
    interests: ["transportation", "mobility", "digital inclusion"],
    populations: ["People without reliable transportation", "Seniors"],
    typicalGrantRange: { min: 5000, max: 35000 },
    deadlineType: "quarterly",
    nextDeadline: "2026-06-05",
    applicationBurden: "low",
    relationshipRequired: "none",
    requiredDocuments: ["determinationLetter"],
    notes: "Auto/mobility company giving program. Brand-aligned mobility projects. Quick application.",
    samplePastGrants: ["$20,000 for ride-program vehicle fuel (sample)"],
    website: "driveforward.example.org",
    isSample: true,
  },
  {
    id: "f-civic-club",
    name: "Downtown Rotary Service Club (Sample)",
    type: "civic club",
    geography: "Local",
    reach: "local",
    interests: ["aging", "transportation", "disability"],
    populations: ["Seniors", "People with disabilities"],
    typicalGrantRange: { min: 1000, max: 10000 },
    deadlineType: "rolling",
    nextDeadline: null,
    applicationBurden: "low",
    relationshipRequired: "helpful",
    requiredDocuments: ["determinationLetter"],
    notes: "Small local grants and volunteer support. Great for relationship-building and pilots.",
    samplePastGrants: ["$5,000 toward dispatch phone line (sample)"],
    website: "downtownrotary.example.org",
    isSample: true,
  },
  {
    id: "f-county-government",
    name: "County Mobility & Aging Services Grant (Sample)",
    type: "government grant",
    geography: "Local",
    reach: "local",
    interests: ["aging", "transportation", "disability", "healthcare access"],
    populations: ["Seniors", "People with disabilities", "Low-income riders"],
    typicalGrantRange: { min: 25000, max: 150000 },
    deadlineType: "annual",
    nextDeadline: "2026-07-31",
    applicationBurden: "high",
    relationshipRequired: "helpful",
    requiredDocuments: ["determinationLetter", "auditedFinancials", "operatingBudget", "programBudget", "evaluationData"],
    notes: "County dollars (often pass-through Older Americans Act). Compliance-heavy reporting.",
    samplePastGrants: ["$100,000 for senior transportation services (sample)"],
    website: "county.example.gov",
    isSample: true,
  },
  {
    id: "f-state-aging",
    name: "State Unit on Aging Transportation Grant (Sample)",
    type: "government grant",
    geography: "Statewide",
    reach: "state",
    interests: ["aging", "transportation", "independence"],
    populations: ["Seniors", "Medically vulnerable people"],
    typicalGrantRange: { min: 50000, max: 250000 },
    deadlineType: "annual",
    nextDeadline: "2026-05-30",
    applicationBurden: "high",
    relationshipRequired: "likely required",
    requiredDocuments: ["determinationLetter", "auditedFinancials", "operatingBudget", "programBudget", "evaluationData", "strategicPlan"],
    notes: "Large state aging grant. Very competitive, heavy compliance, near-term deadline this cycle.",
    samplePastGrants: ["$200,000 multi-county senior rides contract (sample)"],
    website: "state.example.gov",
    isSample: true,
  },
  {
    id: "f-national-aging",
    name: "National Foundation on Healthy Aging (Sample)",
    type: "foundation",
    geography: "National",
    reach: "national",
    interests: ["aging", "social isolation", "healthcare access", "independence"],
    populations: ["Seniors", "Medically vulnerable people"],
    typicalGrantRange: { min: 75000, max: 300000 },
    deadlineType: "invitation only",
    nextDeadline: null,
    applicationBurden: "high",
    relationshipRequired: "likely required",
    requiredDocuments: ["determinationLetter", "auditedFinancials", "evaluationData", "strategicPlan", "impactReport"],
    notes: "Large national funder. Invitation only — requires cultivation and strong evaluation data first.",
    samplePastGrants: ["$250,000 aging-in-place initiative (sample)"],
    website: "healthyaging.example.org",
    isSample: true,
  },
  {
    id: "f-caregiver-support",
    name: "Caregiver Relief Support Fund (Sample)",
    type: "foundation",
    geography: "Regional",
    reach: "state",
    interests: ["caregiver support", "aging", "social isolation", "transportation"],
    populations: ["Seniors", "Medically vulnerable people"],
    typicalGrantRange: { min: 10000, max: 60000 },
    deadlineType: "annual",
    nextDeadline: "2026-09-30",
    applicationBurden: "medium",
    relationshipRequired: "none",
    requiredDocuments: ["determinationLetter", "operatingBudget", "impactReport"],
    notes: "Funds programs that relieve family caregivers — transportation counts as respite/support.",
    samplePastGrants: ["$45,000 for caregiver respite transportation (sample)"],
    website: "caregiverrelief.example.org",
    isSample: true,
  },
  {
    id: "f-social-isolation",
    name: "Connected Communities Loneliness Fund (Sample)",
    type: "foundation",
    geography: "National",
    reach: "national",
    interests: ["social isolation", "aging", "transportation", "independence"],
    populations: ["Seniors", "People without reliable transportation"],
    typicalGrantRange: { min: 20000, max: 90000 },
    deadlineType: "quarterly",
    nextDeadline: "2026-06-25",
    applicationBurden: "medium",
    relationshipRequired: "none",
    requiredDocuments: ["determinationLetter", "evaluationData"],
    notes: "Targets social isolation and loneliness. Wants outcome data on connection, not just rides.",
    samplePastGrants: ["$70,000 to reduce isolation among homebound seniors (sample)"],
    website: "connectedcommunities.example.org",
    isSample: true,
  },
  {
    id: "f-veterans-mobility",
    name: "Veterans Mobility Assistance Fund (Sample)",
    type: "foundation",
    geography: "National",
    reach: "national",
    interests: ["transportation", "disability", "healthcare access", "mobility"],
    populations: ["People with disabilities", "Medically vulnerable people"],
    typicalGrantRange: { min: 15000, max: 80000 },
    deadlineType: "annual",
    nextDeadline: "2026-11-11",
    applicationBurden: "medium",
    relationshipRequired: "none",
    requiredDocuments: ["determinationLetter", "programBudget"],
    notes: "Funds transportation for veterans, especially disabled veterans. Niche population focus.",
    samplePastGrants: ["$60,000 for veteran medical-transport rides (sample)"],
    website: "vetsmobility.example.org",
    isSample: true,
  },
  {
    id: "f-sdoh",
    name: "Healthy Futures SDOH Initiative (Sample)",
    type: "healthcare system",
    geography: "Statewide",
    reach: "state",
    interests: ["healthcare access", "food access", "transportation", "social isolation"],
    populations: ["Low-income riders", "Medically vulnerable people"],
    typicalGrantRange: { min: 40000, max: 200000 },
    deadlineType: "annual",
    nextDeadline: "2026-08-01",
    applicationBurden: "high",
    relationshipRequired: "likely required",
    requiredDocuments: ["determinationLetter", "auditedFinancials", "evaluationData", "impactReport"],
    notes: "Medicaid/social-determinants-adjacent. Transportation as a health intervention. Data-intensive.",
    samplePastGrants: ["$150,000 for SDOH transportation pilot (sample)"],
    website: "healthyfutures.example.org",
    isSample: true,
  },
  {
    id: "f-daf-mobility",
    name: "The Hartwell Family Donor Advised Fund (Sample)",
    type: "donor advised fund",
    geography: "Local",
    reach: "local",
    interests: ["aging", "transportation", "independence"],
    populations: ["Seniors"],
    typicalGrantRange: { min: 5000, max: 50000 },
    deadlineType: "invitation only",
    nextDeadline: null,
    applicationBurden: "low",
    relationshipRequired: "likely required",
    requiredDocuments: ["determinationLetter"],
    notes: "Family DAF that gives to senior-independence causes. Entirely relationship-driven.",
    samplePastGrants: ["$30,000 unrestricted gift to a senior-rides program (sample)"],
    website: "hartwellfund.example.org",
    isSample: true,
  },
  {
    id: "f-digital-inclusion",
    name: "Bridge the Gap Digital Inclusion Fund (Sample)",
    type: "corporate giving",
    geography: "National",
    reach: "national",
    interests: ["digital inclusion", "transportation", "aging"],
    populations: ["People with limited digital access", "Seniors"],
    typicalGrantRange: { min: 10000, max: 50000 },
    deadlineType: "quarterly",
    nextDeadline: "2026-07-01",
    applicationBurden: "low",
    relationshipRequired: "none",
    requiredDocuments: ["determinationLetter"],
    notes: "Tech-company giving for digital equity. Your human-dispatch / no-app model is a strong angle.",
    samplePastGrants: ["$25,000 for phone-based service access (sample)"],
    website: "bridgethegap.example.org",
    isSample: true,
  },
  {
    id: "f-public-private-mobility",
    name: "Regional Transit Public-Private Mobility Grant (Sample)",
    type: "government grant",
    geography: "Regional",
    reach: "state",
    interests: ["transportation", "mobility", "transportation equity", "public-private mobility coordination"],
    populations: ["People without reliable transportation", "Seniors", "People with disabilities"],
    typicalGrantRange: { min: 50000, max: 180000 },
    deadlineType: "annual",
    nextDeadline: "2026-10-01",
    applicationBurden: "high",
    relationshipRequired: "helpful",
    requiredDocuments: ["determinationLetter", "auditedFinancials", "programBudget", "evaluationData"],
    notes: "Coordinates community ride providers with regional transit. Coordination/partnership focus.",
    samplePastGrants: ["$160,000 for first/last-mile coordination (sample)"],
    website: "regionaltransit.example.gov",
    isSample: true,
  },
  {
    id: "f-rural-mobility",
    name: "Rural Roads Mobility Foundation (Sample)",
    type: "foundation",
    geography: "Statewide",
    reach: "state",
    interests: ["transportation", "aging", "healthcare access", "food access"],
    populations: ["Seniors", "Low-income riders", "People without reliable transportation"],
    typicalGrantRange: { min: 15000, max: 70000 },
    deadlineType: "rolling",
    nextDeadline: null,
    applicationBurden: "medium",
    relationshipRequired: "none",
    requiredDocuments: ["determinationLetter", "programBudget"],
    notes: "Funds transportation in transit-scarce areas. Rolling — good fallback opportunity.",
    samplePastGrants: ["$55,000 for rural medical-transport rides (sample)"],
    website: "ruralroads.example.org",
    isSample: true,
  },
  {
    id: "f-youth-arts",
    name: "Bright Futures Youth Arts Foundation (Sample)",
    type: "foundation",
    geography: "Statewide",
    reach: "state",
    interests: ["arts education", "youth development", "after-school"],
    populations: ["Youth", "Students", "K-12 children"],
    typicalGrantRange: { min: 10000, max: 60000 },
    deadlineType: "annual",
    nextDeadline: "2026-09-15",
    applicationBurden: "medium",
    relationshipRequired: "none",
    requiredDocuments: ["determinationLetter", "programBudget"],
    notes: "Funds arts education and youth development. Included to show FundFit recommending SKIP on a clear mismatch.",
    samplePastGrants: ["$30,000 for a youth theater program (sample)"],
    website: "brightfuturesarts.example.org",
    isSample: true,
  },
  {
    id: "f-environmental",
    name: "Green Spaces Environmental Trust (Sample)",
    type: "foundation",
    geography: "National",
    reach: "national",
    interests: ["conservation", "climate", "habitat restoration"],
    populations: ["General public"],
    typicalGrantRange: { min: 50000, max: 250000 },
    deadlineType: "annual",
    nextDeadline: "2026-08-15",
    applicationBurden: "high",
    relationshipRequired: "helpful",
    requiredDocuments: ["determinationLetter", "auditedFinancials", "evaluationData", "strategicPlan"],
    notes: "Funds land conservation and climate work. Included to show a low-fit SKIP recommendation.",
    samplePastGrants: ["$120,000 for wetland restoration (sample)"],
    website: "greenspaces.example.org",
    isSample: true,
  },
  {
    id: "f-womens-giving-circle",
    name: "Metro Women's Giving Circle (Sample)",
    type: "donor advised fund",
    geography: "Local",
    reach: "local",
    interests: ["aging", "social isolation", "caregiver support"],
    populations: ["Seniors", "Medically vulnerable people"],
    typicalGrantRange: { min: 2500, max: 20000 },
    deadlineType: "annual",
    nextDeadline: "2026-06-15",
    applicationBurden: "low",
    relationshipRequired: "helpful",
    requiredDocuments: ["determinationLetter", "boardList"],
    notes: "Collective giving circle. Compelling stories matter more than heavy data. Good story fit.",
    samplePastGrants: ["$12,000 for senior companionship rides (sample)"],
    website: "metrowgc.example.org",
    isSample: true,
  },
];
